version: "2"
services:
  client:
    build: ./front-end
    ports:
      - "80:80"
    depends_on:
      - server
  server:
    build: ./back-end
    ports:
      - "8080:8080"
    volumes:
      - ./volumes/server:/data/server
    depends_on:
      - mongo
  mongo:
    image: mongo
      environment:
        - MONGO_INITDB_DATABASE: "acklen"
      volumes:
        - ./volumes/db:/data/db
      ports:
        - "27017:27017"